name: build-linux-pf 

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cleanup
#        if: ${{ 'true' == 'false' }}
        run: |
          sh ./cleanup.sh
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://aur.archlinux.org/linux-pf.git
      - name: Set UserID
        run: |
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
        env: 
          USERID: ''          
      - name: Build
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build.sh ${{ env.USERID }} 
      - uses: actions/upload-artifact@v4
        with:
          name: linux-pf
          path: ${{ github.workspace }}/linux-pf/*.pkg.tar.zst
